class FormPageLocators:
    FIRST_NAME = '#firstName'
    LAST_NAME = '#lastName'
    EMAIL = '#userEmail'
    GENDER = '[name=gender][value={gender}] + label'
    MOBILE = '#userNumber'
    DATE_OF_BIRTH_INPUT = '#dateOfBirthInput'
    DATE_OF_BIRTH_MONTH_SELECT = '.react-datepicker__month-select'
    DATE_OF_BIRTH_YEAR_SELECT = '.react-datepicker__year-select'
    DATE_OF_BIRTH_DAY = '.react-datepicker__day--0{day}'
    SUBJECTS_INPUT = '#subjectsInput'
    HOBBY = '[for=hobbies-checkbox-{index}]'
    UPLOAD_PICTURE = '#uploadPicture'
    CURRENT_ADDRESS = '#currentAddress'
    STATE = '#state'
    STATE_OPTION = '#react-select-3-option-{index}'
    CITY = '#city'
    CITY_OPTION = '#react-select-4-option-{index}'
    SUBMIT = '#submit'
